"""Render the README dataset tables from the registry (between markers)."""

from __future__ import annotations

from pathlib import Path

from rirdb.registry import Dataset

BEGIN = "<!-- BEGIN DATASETS (generated by `rirdb registry compile`; edit registry/datasets.yaml) -->"
END = "<!-- END DATASETS -->"

_FORMAT_LABELS = {
    "mono_omni": "mono",
    "stereo": "stereo",
    "binaural": "binaural",
    "foa_fuma": "FOA (FuMa)",
    "foa_ambix": "FOA (ambiX)",
    "hoa_sh": "HOA",
    "em32_raw": "em32",
    "sma_raw": "spherical array",
    "tetra_raw": "A-format",
    "array_raw": "array",
    "sdm_array": "SDM array",
}

_COLUMNS = ("Name", "Content", "IRs", "Rooms", "Format", "fs", "License", "Year", "Paper", "Get")


def _esc(text: str) -> str:
    return text.replace("|", "\\|")


def _license(d: Dataset) -> str:
    spdx = d.license.spdx
    if spdx == "LicenseRef-unspecified":
        label = "unspecified"
    elif spdx.startswith("LicenseRef-"):
        label = "custom"
    else:
        label = spdx.replace("-only", "")
    return f"[{label}]({d.license.url})" if d.license.url else label


def _fs(d: Dataset) -> str:
    if not d.fs_hz:
        return "?"
    return ", ".join(f"{f / 1000:g}k" for f in sorted(set(d.fs_hz)))


def _count(n: int | None) -> str:
    return f"{n:,}" if n else "?"


def _get(d: Dataset) -> str:
    if d.status == "deferred":
        return "later"
    if d.access in ("manual", "registration") or d.status == "manual":
        return "manual"
    if d.status == "broken":
        return "broken"
    return f"W{d.wave} :heavy_check_mark:"


def _row(d: Dataset) -> str:
    name = f"[{_esc(d.name)}]({d.homepage})" if d.homepage else _esc(d.name)
    paper = f"[{_esc(d.paper.title)}]({d.paper.url})" if d.paper else (f"[doi]({'https://doi.org/' + d.doi})" if d.doi else "")
    content = _esc(d.content)
    if d.expected.note:
        content += f" _({_esc(d.expected.note)})_"
    cells = (
        name,
        content,
        _count(d.expected.n_irs),
        _count(d.expected.n_rooms),
        ", ".join(_FORMAT_LABELS[f] for f in d.capture_formats),
        _fs(d),
        _license(d),
        str(d.year or ""),
        paper,
        _get(d),
    )
    return "| " + " | ".join(cells) + " |"


def _table(rows: list[Dataset]) -> str:
    rows = sorted(rows, key=lambda d: (-(d.year or 0), d.name.lower()))
    head = "| " + " | ".join(_COLUMNS) + " |"
    sep = "| " + " | ".join(":--" if c in ("Name", "Content") else ":-:" for c in _COLUMNS) + " |"
    return "\n".join([head, sep, *(_row(d) for d in rows)])


def render_tables(datasets: list[Dataset]) -> str:
    measured = [d for d in datasets if d.type == "measured"]
    sections = [
        ("Measured: omnidirectional and microphone arrays", [d for d in measured if not d.spatial]),
        ("Measured: spatial (Ambisonic / spherical arrays) and binaural", [d for d in measured if d.spatial]),
        ("Production IR libraries", [d for d in datasets if d.type == "production"]),
        ("Simulated (planned: wave 4, after the corpus moves to permanent storage)", [d for d in datasets if d.type == "simulated"]),
    ]
    n_fetch = sum(d.fetchable for d in datasets)
    out = [
        BEGIN,
        "",
        f"{len(datasets)} datasets tracked, {n_fetch} fetched automatically by the pipeline. "
        "**Get**: `W<n>` is the download wave (0 smoke, 1 many spaces, 2 multi-condition, "
        "3 dense grids); `manual` needs registration or a browser download; `later` is not yet scheduled. "
        "Counts are as reported by the authors; `?` means not yet confirmed by `rirdb probe`.",
    ]
    for title, rows in sections:
        if rows:
            out += ["", f"### {title}", "", _table(rows)]
    out += ["", END]
    return "\n".join(out)


def update_readme(readme: Path, datasets: list[Dataset]) -> bool:
    """Replace the generated block in the README. Returns True if the file changed."""
    text = readme.read_text()
    if BEGIN not in text or END not in text:
        raise ValueError(f"{readme} has no generated-dataset markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + render_tables(datasets) + tail
    if new == text:
        return False
    readme.write_text(new)
    return True
