"""Dataset cards: docs/datasets/<id>.md, generated from the registry and the metrics."""

from __future__ import annotations

import numpy as np
import pandas as pd

from rirdb import paths
from rirdb.query import connect
from rirdb.registry import Dataset, load_registry

PARAMS = [("t30_mid", "T30 mid (s)", 2), ("edt_mid", "EDT mid (s)", 2), ("c80_mid", "C80 mid (dB)", 1),
          ("d50_mid", "D50 mid", 2), ("ts_mid", "Ts mid (s)", 3), ("drr_bb", "DRR (dB)", 1),
          ("sti", "STI", 2), ("br", "Bass ratio", 2), ("tr", "Treble ratio", 2),
          ("t_mix_ned_ms", "Mixing time (ms)", 0), ("iacc_e3", "IACC_E3", 2), ("jlf_low", "JLF", 2)]


def _q(s: pd.Series, nd: int) -> str:
    s = s.dropna()
    if s.empty:
        return "| | | | |"
    return "| " + " | ".join(f"{v:.{nd}f}" for v in s.quantile([0.1, 0.5, 0.9])) + f" | {len(s):,} |"


def card(d: Dataset, m: pd.DataFrame, rooms: pd.DataFrame) -> str:
    lic = d.license
    lines = [
        f"# {d.name}",
        "",
        f"`{d.id}` · {d.type} · {d.year or 'n/a'} · wave {d.wave if d.wave is not None else '-'} · status **{d.status}**",
        "",
        d.content,
        "",
        "## Provenance and terms",
        "",
        f"- Source: {d.source.kind} {' '.join(d.source.records or d.source.urls)}",
        f"- Homepage: {d.homepage or '-'}",
        f"- Paper: {f'[{d.paper.title}]({d.paper.url})' if d.paper else '-'}" + (f" · DOI {d.doi}" if d.doi else ""),
        f"- Licence: {lic.spdx}" + (f" ({lic.url})" if lic.url else ""),
        f"- Audio redistribution: **{lic.redistribute_audio}** · ML training use: **{lic.training}**",
    ]
    if lic.note:
        lines.append(f"- Licence note: {lic.note}")
    if d.notes:
        lines.append(f"- Notes: {d.notes}")
    lines += ["", "## Contents", ""]
    if m.empty:
        lines += ["Not analysed yet.", ""]
        return "\n".join(lines)
    grades = m["grade"].value_counts()
    lines += [
        f"- IRs analysed: **{len(m):,}** (reported by the authors: {d.expected.n_irs or '?'}"
        + (f"; {d.expected.note}" if d.expected.note else "") + ")",
        f"- Rooms/spaces: {m['room_id'].nunique()} · sample rates: {', '.join(str(int(f)) for f in sorted(m['fs'].dropna().unique()))} Hz",
        f"- Capture: {', '.join(sorted(m['capture_format'].dropna().unique()))}; analysed channel(s): "
        f"{', '.join(sorted(m['analysed_role'].dropna().unique()))}",
        f"- Grades: " + ", ".join(f"{k} {int(grades.get(k, 0)):,}" for k in "ABCD"),
        f"- Analysis errors: {int((m['error'].fillna('') != '').sum())}",
        "",
        "## Parameters (10th / 50th / 90th percentile, valid values)",
        "",
        "| parameter | p10 | p50 | p90 | n |",
        "|---|---|---|---|---|",
    ]
    for col, label, nd in PARAMS:
        if col in m and m[col].notna().any():
            lines.append(f"| {label} " + _q(m[col], nd))
    flags = [c for c in m.columns if c.startswith("flag_")]
    rates = (m[flags].astype(float).mean() * 100).sort_values(ascending=False)
    rates = rates[rates >= 1]
    if not rates.empty:
        lines += ["", "## Quality flags (% of IRs)", "", "| flag | % |", "|---|---|"]
        lines += [f"| {c[5:].replace('_', ' ')} | {v:.0f} |" for c, v in rates.items()]
    r = rooms[rooms["dataset_id"] == d.id]
    if not r.empty:
        cols = [c for c in ("room_key", "room_label", "category", "ir_kind", "volume_m3", "n_irs") if c in r]
        rr = r[cols].sort_values("room_key").head(60)
        lines += ["", f"## Rooms ({len(r)}; first 60)", "", "| " + " | ".join(cols) + " |",
                  "|" + "---|" * len(cols)]
        for row in rr.itertuples(index=False):
            lines.append("| " + " | ".join("" if (isinstance(v, float) and np.isnan(v)) else
                                           (f"{v:.0f}" if isinstance(v, float) else str(v)) for v in row) + " |")
    lines += ["", "_Generated by `rirdb report cards`; methods: docs/decisions/analyzer-v1.md._", ""]
    return "\n".join(lines)


def build() -> list:
    con = connect()
    m_all = con.execute("SELECT * FROM corpus").df()
    rooms = con.execute("SELECT * FROM rooms").df()
    out_dir = paths.REPO_ROOT / "docs" / "datasets"
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for d in load_registry():
        m = m_all[m_all["dataset_id"] == d.id]
        p = out_dir / f"{d.id}.md"
        p.write_text(card(d, m, rooms))
        written.append(p)
    return written
